### ISSUE TITLE
Unable to Use "sourceCpp" to load mLDM Package

### ISSUE THREAD

**Issue by ktmcc-ucsf** [tinglab/mLDM#1]
Hi,

I would like to use "Usage" method 2.1 to download the mLDM package. I downloaded and loaded all of the packages as specified, but when I try to use `sourceCpp("mLDM.cpp")`, I get the following error:

`Error in eval(substitute(expr), envir, enclos) : 
  file not found: 'mLDM.cpp'
In addition: Warning message:
In normalizePath(file, winslash = "/") :
  path[1]="mLDM.cpp": No such file or directory
`

I am accessing a server from a terminal on Mac, and therefore would prefer to install directly from the R console, as opposed to downloading the .tar.gz file and then uploading to the server, if at all possible.

**Comment by tinglab** [comment]
You need to specify the path of the source code file 'mLDM.cpp', and then run the command 'sourceCpp(PATH/mLDM.cpp)'. Did you do it right ?
